# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/toost',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/toost',
                'lib_path': 'toost'},
  'syms': {'toost.core': {'toost.core.foo': ('core.html#foo', 'toost/core.py')}}}
